### ISSUE TITLE
Clarification about "point index"?

### ISSUE THREAD

**Issue by mourner** [IMQS/flatbush#1]
> Note that this is actually a point index, so you are only guaranteed to find an object when it's center lies inside the query box.

I'm confused about this point in the readme... Flatbush makes a rectangle index and returns intersecting rectangles on search. Is this not the case for the port?

**Comment by bmharper** [comment]
When scanning the leaves, rectangles are tested for intersection. However, the hierarchical search that traverses the tree is operating on an index that was built from the center point of the bounding box of the object.
I was surprised by this, when I tried some queries, and noticed that I was not guaranteed to get a result back, unless the indexed item's center was inside the query box.
Exact same behaviour as the js version.
Does that make sense?

**Comment by mourner** [comment]
@bmharper it doesn't — you should get all intersecting rectangles in the result. If it doesn't, please make a minimal test case (with as few items as possible while still reproducing the issue), and submit an issue to Flatbush. How index is built doesn't affects the search semantics, only its performance.

**Comment by bmharper** [comment]
Will do!

**Comment by bmharper** [comment]
Sorry - looks like my mistake. It must have been a bug in my initial port where I saw this. I can't reproduce this issue anymore in the C++ version or the JS version.

**Comment by mourner** [comment]
Great!
